apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: elasticsearch
spec:
  entryPoints:
    - {{.Values.ingressRoute.entryPointName}}
  routes:
    - kind: Rule
      match: Host(`{{.Values.ingressRoute.adminDomain}}`)  && PathPrefix(`/elasticsearch`)
      middlewares:
        - name: strip-prefix-{{ .Release.Name }}
          namespace: {{ .Release.Namespace }}
      services:
        - kind: Service
          name: elasticsearch-master
          namespace: {{.Release.Namespace}}
          passHostHeader: true
          port: 9200