{{- with .Values.replaceImageRegistry }}
{{- if .enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{.name}}
  annotations:
    policies.kyverno.io/title: Replace Image Registry
    pod-policies.kyverno.io/autogen-controllers: {{ .autogenControllers }}
    policies.kyverno.io/category: DockerImage
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      We rewrite every third party docker registry to `{{.target}}`.
      If the image does not exist there it can not be deployed.

      Since we have also business apps you can also exclude registries from the replacement.

      The pulls are directed to a approved registry. In some cases, those registries may function as
      pull-through proxies and can fetch the image if not cached.
      This policy mutates all images either in the form 'image:tag' or
      'registry.corp.com/image:tag' to be `{{ .target | trimSuffix "/" }}/image:tag`.
      Note that this mutates Pods directly and not their controllers. It can be changed if desired but
      if so may need to not match on Pods.
spec:
  generateExistingOnPolicyUpdate: false
  background: true
  rules:
    - name: {{ .name }}
      match:
        any:
          - resources:
              kinds:
                - Pod
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            preconditions:
              all:
                {{- range $excludeRegistry := .excludeRegistries}}
                - key: "{{`{{element.image}}`}}"
                  operator: NotEquals
                  value: "{{$excludeRegistry}}"
                {{- end }}
            patchStrategicMerge:
              metadata:
                annotations:
                  +(clusterpolicies.kyverno.io/{{ .name }}): "Replaced the containers image registry with {{ .target }}"
              spec:
                containers:
                  - name: "{{`{{ element.name }}`}}"
                    image: "{{ `{{ regex_replace_all(` }} {{ .sourceRegex }} {{ `, '{{ element.image }}', '` }}{{ .target | trimSuffix "/" }}{{ `/$2' )}}` }}"
    - name: {{ .name }}-initcontainers
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{`{{ request.object.spec.initContainers[] || `}}`[]`{{` | length(@) }}`}}"
            operator: GreaterThanOrEquals
            value: 1
      mutate:
        foreach:
          - list: "request.object.spec.initContainers"
            preconditions:
              all:
                {{- range $excludeRegistry := .excludeRegistries}}
                - key: "{{`{{element.image}}`}}"
                  operator: NotEquals
                  value: "{{$excludeRegistry}}"
                {{- end }}
            patchStrategicMerge:
              metadata:
                annotations:
                  +(clusterpolicies.kyverno.io/{{ .name }}-initcontainers): "Replaced the initContainers image registry with {{ .target }}"
              spec:
                initContainers:
                  - name: "{{`{{ element.name }}`}}"
                    image: "{{ `{{ regex_replace_all(` }} {{ .sourceRegex }} {{ `, '{{ element.image }}', '` }}{{ .target | trimSuffix "/" }}{{ `/$2' )}}` }}"

---
{{- end }}
{{- end }}
