apiVersion: v2
description: oidc-forward-auth
name: oidc-forward-auth
version: 1.1.2
dependencies:
  - name: gatekeeper
    repository: https://gogatekeeper.github.io/helm-gogatekeeper
    version: 0.1.33