credentials:
  password: "DUMMY_VALUE"
ollama:
  webui:
    env:
      OLLAMA_API_BASE_URL: "https://ollama.my-domain.com/api"
webui:
  env:
    OLLAMA_API_BASE_URL: "https://ollama.my-domain.com/api"

traefik:
  metrics:
    prometheus:
      disableAPICheck: true