upstream:
  service:
    name: traefik-websecure-internal
    port: 8444

ingressRoute:
  adminDomain: "admin.my-domain.com"
  entryPointName: "websecure"
  certificate:
    name: admin
    clusterIssuer: letsencrypt