#https://doc.traefik.io/traefik/middlewares/http/basicauth/
credentials:
  username: "admin"
  password:
ingressRoute:
  upstream:
    service:
      name: traefik-internal
      port: 8444
  domain: "admin.my-domain.com"
  entryPointName: "websecure"
  certificate:
    # Defaults to .Release.Name -cert
    name:
    clusterIssuer: letsencrypt