{{- if (eq (index .Values.ingress.enabled) true) }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-{{ .Release.Name }}
spec:
  stripPrefix:
    prefixes:
      - "/policies"
{{- end }}