{{ if .Values.ingressRoute.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{.Release.Name}}-ui
spec:
  entryPoints:
    - {{ .Values.ingressRoute.entryPointName }}
  routes:
    - kind: Rule
      match: Host(`{{.Values.ingressRoute.adminDomain}}`)  && PathPrefix(`{{.Values.ingressRoute.pathPrefix}}`)
      middlewares:
        - name: strip-prefix-{{ .Release.Name }}
          namespace: {{.Release.Namespace}}
      services:
        - kind: Service
          name: {{ .Release.Name }}-ui
          namespace: {{.Release.Namespace}}
          passHostHeader: true
          port: 8080
{{ end }}