{{ with .Values.policyException }}
{{ if .enabled }}
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: prometheus-stack-prometheus-node-exporter
  namespace: {{ .namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  exceptions:
    - policyName: restrict-volume-types-strict
      ruleNames:
        - restricted-volumes
        - autogen-restricted-volumes
    - policyName: restrict-volume-types
      ruleNames:
        - restricted-volumes
        - autogen-restricted-volumes
    - policyName: disallow-host-namespaces
      ruleNames:
        - host-namespaces
    - policyName: disallow-host-ports
      ruleNames:
        - host-ports-none
    - policyName: disallow-host-path
      ruleNames:
        - host-path
  match:
    any:
      - resources:
          kinds:
            - DaemonSet
            - Pod
          name:
            - prometheus-stack-prometheus-node-exporter*
          namespaces:
            - {{ $.Release.Namespace }}
{{- end }}
{{- end }}