apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: elasticsearch
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  exceptions:
    - policyName: enforce-security-context
      ruleNames:
        - add-pod-security-context
    - policyName: require-run-as-non-root-user
      ruleNames:
        - run-as-non-root-user
    - policyName: require-run-as-nonroot
      ruleNames:
        - run-as-non-root
    - policyName: restrict-seccomp-strict
      ruleNames:
        - check-seccomp-strict
    - policyName: disallow-capabilities-strict
      ruleNames:
        - require-drop-all
    - policyName: disallow-privilege-escalation
      ruleNames:
        - privilege-escalation
    - policyName: disallow-privileged-containers
      ruleNames:
        - privileged-containers
  match:
    any:
      - resources:
          kinds:
            - Pod
          names:
            - elasticsearch-master*
            - elastic-stack-ilm*
            - elastic-stack-index*
            - elastic-stack-backup*
          namespaces:
            - monitoring