apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: elasticsearch
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  exceptions:
    - policyName: enforce-security-context
      ruleNames:
        - add-pod-security-context
  match:
    any:
      - resources:
          kinds:
            - Pod
          names:
            - elasticsearch-master*
          namespaces:
            - monitoring