{{- if .Values.middleware.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm-middleware.serviceAccountName" . }}
  labels:
    {{- include "llm-middleware.labels" . | nindent 4 }}
  {{- with .Values.middleware.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
