apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-middleware.fullname" . }}
  labels:
    {{- include "llm-middleware.labels" . | nindent 4 }}
spec:
  type: {{ (.Values.middleware.service).serviceType | default "ClusterIP"}}
  ports:
    {{- range $name,$values := .Values.middleware.service.ports }}
    - targetPort: {{ ($values).targetPort | default 80 }}
      name: {{ ($values).name | default $name }}
      protocol: {{ ($values).protocol | default "TCP"}}
      port: {{($values).port | default 80 }}
    {{- end }}
  selector:
    {{- include "llm-middleware.selectorLabels" . | nindent 4 }}
