apiVersion: v2
name: iits-ollama-fullstack
description: |
  Setup private LLM RAG Cluster with (weaviate, Ollama & airbyte)
  
  ## Installing the Chart with iits ArgoCD

  # Register the Chart

  ```yaml
    iits-ollama-fullstack:
      targetRevision: "0.2.4"
      namespace: ollama
      valueFile: "value-files/iits-ollama-fullstack/values.yaml"
  ```

  value-files/iits-ollama-fullstack/values.yaml

  ```yaml
  ingress:
    airbyte:
      host: "airbyte.ollama.my-domain.com"
      annotations:
        # Adds the oidc proxy upfront
        traefik.ingress.kubernetes.io/router.middlewares: "ollama-oidc-forward-auth-ollama@kubernetescrd"
  ollama:
    ollama:
      ollama:
        gpu:
          enabled: "true"
      ingress:
        host: "ollama.my-domain.com"
        annotations:
          # Adds the oidc proxy upfront
          traefik.ingress.kubernetes.io/router.middlewares: "ollama-oidc-forward-auth-ollama@kubernetescrd, ollama-strip-prefix-ollama@kubernetescrd"
    webui:
      env:
        OLLAMA_API_BASE_URL: "https://ollama.my-domain.com/api"
      ingress:
        annotations:
          # Adds the oidc proxy upfront
          traefik.ingress.kubernetes.io/router.middlewares: "ollama-oidc-forward-auth-ollama@kubernetescrd"
        host: "ollama.my-domain.com"
  ```
type: application
version: 0.2.6
home: https://ollama.ai/
icon: https://ollama.ai/public/ollama.png
keywords:
  - ai
  - llm
  - llama
  - mistral
dependencies:
  - name: weaviate
    repository: https://weaviate.github.io/weaviate-helm
    version: 16.8.1
    condition: weaviate.enabled
  - name: airbyte
    version: 0.53.137
    repository: https://airbytehq.github.io/helm-charts
    condition: airbyte.enabled
  - name: ollama
    version: 0.6.14
    repository: https://charts.iits.tech
    condition: ollama.enabled