apiVersion: v2
name: iits-ollama-fullstack
description: |
  Setup private LLM RAG Cluster with (weaviate, Ollama & airbyte)
  
  ## Installing the Chart with iits ArgoCD

  # Register the Chart

  ```yaml
    iits-ollama-fullstack:
      targetRevision: "0.4.0"
      namespace: ollama
      valueFile: "value-files/iits-ollama-fullstack/values.yaml"
  ```

  value-files/iits-ollama-fullstack/values.yaml

  ```yaml
  airbyte:
    fullnameOverride: "airbyte"
    webapp:
      ingress:
        enabled: true
        hosts:
          - host:
            paths:
              - path: "/"
                pathType: "Prefix"
        annotations:
          # Adds the oidc proxy upfront
          traefik.ingress.kubernetes.io/router.middlewares: "ollama-oidc-forward-auth-ollama@kubernetescrd"

    connector-builder-server:
      service:
        type: "ClusterIP"
  ollama:
    ollama:
      ollama:
        gpu:
          enabled: "true"
      ingress:
        host: "ollama.my-domain.com"
        annotations:
          # Adds the oidc proxy upfront
          traefik.ingress.kubernetes.io/router.middlewares: "ollama-oidc-forward-auth-ollama@kubernetescrd, ollama-strip-prefix-ollama@kubernetescrd"
    webui:
      env:
        OLLAMA_API_BASE_URL: "https://ollama.my-domain.com/api"
      ingress:
        annotations:
          # Adds the oidc proxy upfront
          traefik.ingress.kubernetes.io/router.middlewares: "ollama-oidc-forward-auth-ollama@kubernetescrd"
        host: "ollama.my-domain.com"
    middleware:
      env:
        OLLAMA_URL: "http://ollama:11434"
        WEAVIATE_URL: "http://weaviate:80"
        OPENAI_API_TOKEN: "REPLACE_ME"
      ingress:
        annotations:
          # Adds the oidc proxy upfront
          traefik.ingress.kubernetes.io/router.middlewares: "ollama-oidc-forward-auth-ollama@kubernetescrd"
        host: "ollama.my-domain.com"
  ```
type: application
version: 0.4.0
home: https://ollama.ai/
icon: https://ollama.ai/public/ollama.png
keywords:
  - iits AI
  - RAG
dependencies:
  - name: weaviate
    repository: https://weaviate.github.io/weaviate-helm
    version: 16.8.7
    condition: weaviate.enabled
  - name: airbyte
    version: 0.55.5
    repository: https://airbytehq.github.io/helm-charts
    condition: airbyte.enabled
  - name: ollama
    version: 0.19.0
    repository: https://otwld.github.io/ollama-helm/
    condition: airbyte.enabled