apiVersion: v2
appVersion: 10.22.0
dependencies:
- name: traefik
  repository: https://helm.traefik.io/traefik
  version: 10.22.0
description: traefik
name: traefik
version: 10.22.0-bugfix-traefik-annotations
