traefik:
  globalArguments:
    - "--global.checknewversion"
  additionalArguments:
    - "--ping"
  api:
    dashboard: true
    insecure: true
  ping:
    manualRouting: true
  logs:
    general:
      format: json
      level: INFO
    access:
      format: json
      enabled: false
  deployment:
    replicas: 2
  service:
    type: LoadBalancer
    spec:
      externalTrafficPolicy: Cluster
  ports:
    after-proxy:
      exposedPort: 8444
      port: 8444
      expose: false
      protocol: TCP
      tls:
        enabled: false
  providers:
    kubernetesCRD:
      enabled: true
    kubernetesIngress:
      enabled: true

ingressRoute:
  adminDomain: "admin.my-domain.com"
