{{- $afterProxyPort := index .Values.traefik.ports "after-proxy"}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-websecure-internal
spec:
  type: ClusterIP
  ports:
    - port: {{$afterProxyPort.port}}
      targetPort: {{$afterProxyPort.port}}
      protocol: TCP
      name: after-proxy
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: {{ .Release.Name }}