ingressRoute:
  domain: "my-domain.com"
  entryPointName: "websecure"
  certificate:
    # Defaults to .Release.Name -cert
    name:
    clusterIssuer: letsencrypt
keycloak:
  logging:
    output: "json"
  image:
    # As we won't necessarily update the version when changing the container
    # we enforce pulling the image
    pullPolicy: Always
  proxyAddressForwarding: true
  replicaCount: 2
  service:
    type: ClusterIP
  postgresql:
    enabled: false
  auth:
    # -- Required
    adminUser: "REPLACE_ME"
    # -- Required
    adminPassword: "REPLACE_ME"
  externalDatabase:
    # -- Required
    user: "REPLACE_ME"
    # -- Required, replace it with your host address
    host: "REPLACE_ME"
    # -- Required
    database: "REPLACE_ME"
    # -- Required
    port: "REPLACE_ME"