apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: {{.Values.name}}-controller
  name: {{.Values.name}}-controller
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      control-plane: {{.Values.name}}-controller
  template:
    metadata:
      labels:
        control-plane: {{.Values.name}}-controller
    spec:
      imagePullSecrets:
        - name: dockerhub-config-{{.Values.defaultClusterPullSecret.dockerConfigJsonBase64Encoded | sha256sum}}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: controller
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          args:
            - --enable-leader-election
          command:
            - /controller
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 10

      