apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: {{.Values.name}}-controller
  name: {{.Values.name}}-controller
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      control-plane: {{.Values.name}}-controller
  template:
    metadata:
      labels:
        control-plane: {{.Values.name}}-controller
    spec:
      securityContext:
        runAsNonRoot: true
      imagePullSecrets:
        - name: dockerhub-config-json
      containers:
        - name: controller
          securityContext:
            allowPrivilegeEscalation: false
          args:
            - --enable-leader-election
          command:
            - /controller
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy}}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: 10
