{{- $configChecksum := include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
{{- $defaultValues := .Values.kasmDefaultConfig }}
{{ range $serviceName,$serviceValues := .Values.services }}
{{- $certSecretName := (($serviceValues.ingressRoute).certificate).name | default (printf "%s-%s" $serviceName "cert")}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ default $serviceName $serviceValues.nameOverride }}
spec:
  selector:
    matchLabels:
      app: {{ default $serviceName $serviceValues.nameOverride }}
      release: {{ default $serviceName $serviceValues.nameOverride }}
  replicas: {{ default $defaultValues.replicaCount $serviceValues.replicaCount }}
  template:
    metadata:
      annotations:
        configChecksum: {{ $configChecksum }}
      labels:
        app: {{ default $serviceName $serviceValues.nameOverride }}
        release: {{ default $serviceName $serviceValues.nameOverride }}
    spec:
      securityContext:
        {{- toYaml (default $defaultValues.podSecurityContext $serviceValues.podSecurityContext) | nindent 8 }}
      containers:
        - name: {{ default $serviceName $serviceValues.nameOverride }}
          image: {{ default $defaultValues.image.repository ($serviceValues.image).repository }}:{{ default $defaultValues.image.tag ($serviceValues.image).tag }}
          imagePullPolicy: {{ default "IfNotPresent" ($serviceValues.image).pullPolicy }}
          securityContext:
            {{- toYaml (default $defaultValues.securityContext  $serviceValues.securityContext) | nindent 12 }}
          resources:
            {{- toYaml (default $defaultValues.resources  $serviceValues.resources) | nindent 12 }}
          ports:
            - name: app-internal
              containerPort: {{ default $defaultValues.service.port ($serviceValues.service).port }}
          env:
            {{- range $key, $value := $defaultValues.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := $serviceValues.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: {{ $.Release.Name }}-config
              mountPath: /etc/kasmvnc
            - name: {{ $.Release.Name }}-cert
              mountPath: /opt/kasm/current/certs
              readOnly: true
            - name: user-data
              mountPath: /home/kasm-user
      volumes:
        - name: {{ $.Release.Name }}-config
          secret:
            secretName: {{ $.Release.Name }}-config
            defaultMode: 0777
        - name: {{ $.Release.Name }}-cert
          secret:
            secretName: {{$certSecretName}}
  volumeClaimTemplates:
    - metadata:
        name: user-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi

---
{{- end }}