apiVersion: v2
dependencies:
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 8.5.1
- condition: kibana.enabled
  name: kibana
  repository: https://helm.elastic.co
  version: 8.5.1
- condition: filebeat.enabled
  name: filebeat
  repository: https://helm.elastic.co
  version: 8.5.1
name: elasticsearch
version: 8.9.2
appVersion: 8.5.1
description: |
  Elasticsearch + filebeat + kibana with default common used indexes and Index Lifecycle Management.  
  It comes also with a backup functionality.
