apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-index-pattern-init-config
data:
  index-pattern-init.sh: |
    #!/bin/sh
    {{- range $indexName,$indexValues  := .Values.indexPatternInit.indices }}
    # Apply default Index Pattern into Kibana
    echo "create index pattern {{$indexName}}"
    curl -s -X POST {{$.Release.Name}}-kibana:5601{{ index $.Values.kibana.ingress.hosts 0 "paths" 0 "path"}}/api/data_views/data_view \
    -H 'kbn-xsrf: true' -H 'Content-Type: application/json' --data-binary @- << EOF
        {
          "override": true,
          "data_view": {
            "title": "{{$indexName}}*" ,
            "timeFieldName": "{{$indexValues.timestampField}}",
            "allowNoIndex": true
          }
        }
    EOF

    echo
    echo "create index pattern {{$indexName}} finished"
    {{ end }}