apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.elasticsearch.backup.job.name}}-pvc
spec:
  accessModes:
    - {{.Values.elasticsearch.backup.volume.accessMode}}
  resources:
    requests:
      storage: {{.Values.elasticsearch.backup.volume.storage}}
  storageClassName: {{.Values.elasticsearch.backup.volume.storageClassName}}
  volumeName: {{.Values.elasticsearch.backup.job.name}}-pv