{{- if .Values.source.external -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "swagger-ui.fullname" . }}
  labels:
    app: {{ template "swagger-ui.name" . }}
    chart: {{ template "swagger-ui.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  conf.json: |-
{{ range (.Values.source.external | b64dec) | toStrings }}
{{ . | nindent 4 }}
{{ end }}

{{- else -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "swagger-ui.fullname" . }}
  labels:
    app: {{ template "swagger-ui.name" . }}
    chart: {{ template "swagger-ui.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  conf.json: |-
{{- .Files.Get .Values.source.internal.path | nindent 4 -}}
{{- end -}}
