allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  {{- if .Values.kmsId }}
  name: csi-nas-retain-encrypted
  {{- else }}
  name: csi-nas-retain
  {{- end }}
parameters:
  csi.storage.k8s.io/csi-driver-name: nas.csi.everest.io
  csi.storage.k8s.io/fstype: nfs
  everest.io/share-access-level: rw
  everest.io/share-is-public: "false"
  everest.io/zone: eu-de-01
  {{- if .Values.kmsId }}
  everest.io/crypt-key-id: {{ $.Values.kmsId }}
  {{- end }}
provisioner: everest-csi-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate