{{ range $projectName,$project := .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $projectName }}
spec:
  sourceRepos:
    - {{ $project.git.repoUrl }}
    {{- if $project.allowedUrls -}}
    {{- range $allowedUrl := $project.allowedUrls }}
    - {{ $allowedUrl }}
    {{- end }}
    {{ else }}
    - "*"
    {{- end }}
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
{{- end }}
