{{- range $serviceName,$serviceValues := .Values.services }}
{{- if $serviceValues.dnsEndpointEnabled }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{$serviceName}}
  annotations:
    autoInjectPublicIP: 'true'
spec:
  endpoints:
    - dnsName: {{$serviceValues.ingressRoute.domain}}
      recordTTL: 180
      recordType: A
      targets:
        - SET_BY_KYVERNO
---
{{- end }}
{{- end }}