apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-backup-config
data:
  configure-backup.sh: |
    #!/bin/sh
    set -eu

    endpoint="elasticsearch-master:9200"

    echo -e "\nINFO: Creating S3 snapshot repository {{ .Values.backup.repoName }}"
    curl -s -X PUT --header 'Content-Type: application/json' ${endpoint}/_snapshot/{{ .Values.backup.repoName }} --data-binary @- << EOF

      {
        "type": "s3",
        "settings": {
          "endpoint": "${S3_BUCKET_ENDPOINT}",
          "bucket": "${S3_BUCKET_NAME}",
          "access_key": "${S3_BUCKET_ACCESS_KEY}",
          "secret_key": "${S3_BUCKET_SECRET_KEY}"
        }
      }
    EOF

    echo -e "\nINFO: S3 snapshot repository {{ .Values.backup.repoName }} created!"

    echo -e "\nINFO: Creating SLM policy {{ .Values.backup.policy.name }}"
    curl -s -X PUT --header 'Content-Type: application/json' ${endpoint}/_slm/policy/{{ .Values.backup.policy.name }} --data-binary @- << EOF


      {
        "schedule": "{{ .Values.backup.policy.schedule }}",
        "name": "<{{ .Values.backup.policy.name }}-{now/d}>",
        "repository": "{{ .Values.backup.repoName }}",
        "config": {
          "indices": {{.Values.backup.policy.indices | toJson }},
          "ignore_unavailable": false,
          "include_global_state": true
        },
        "retention": {
          "expire_after": "{{ .Values.backup.policy.retention.expireAfter }}",
          "min_count": {{ .Values.backup.policy.retention.minCount }},
          "max_count": {{ .Values.backup.policy.retention.maxCount }}
        }
      }
    EOF

    echo -e "\nINFO: SLM policy {{ .Values.backup.policy.name }} created!"
