apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name}}-backup-init
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-5"
    checksum/config: {{ include (print $.Template.BasePath "/backup/config.yaml") . | sha256sum | substr 0 50 }}
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: {{.Release.Name}}-backup-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{.Release.Name}}-backup-init
          image: {{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag }}
          imagePullPolicy: IfNotPresent
          command: ['/bin/sh', '-c']
          args: ["/backup-config/configure-backup.sh"]
          volumeMounts:
            - name: backup-config
              mountPath: /backup-config
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-backup-init-env
      volumes:
        - name: backup-config
          configMap:
            name: {{.Release.Name}}-backup-config
            defaultMode: 0755