apiVersion: v2
name: kyverno
description: |
  This chart wraps the upstream `kyverno` and `kyverno-policies` chart and adds a few useful policies:
    - Verify all images are signed with cosign
    - Verify all images come from allowed image repositories
    - Replace the complete registry reference with a custom one
    - Prepend the image reference with a custom prefix, useful for e.g. pull-through caches
dependencies:
  - name: "kyverno"
    repository: "https://kyverno.github.io/kyverno/"
    version: 3.2.4
  - name: "policy-reporter"
    repository: "https://kyverno.github.io/policy-reporter"
    version: 2.23.1
    condition: policy-reporter.install
  - name: "kyverno-policies"
    repository: "https://kyverno.github.io/kyverno/"
    version: 3.2.3
type: application
version: 2.1.0
appVersion: 3.2.4