apiVersion: v2
name: kyverno
description: |
  This chart wraps the upstream `kyverno` chart.
dependencies:
  - name: "kyverno"
    repository: "https://kyverno.github.io/kyverno/"
    version: 3.2.0
  - name: "policy-reporter"
    repository: "https://kyverno.github.io/policy-reporter"
    version: 2.22.5
type: application
version: 2.0.0
appVersion: 3.2.0