kyverno:
  features:
    logging:
      format: text
    policyExceptions:
      namespace: 'kyverno'

  admissionController:
    replicas: 2
    serviceMonitor:
      enabled: true

  backgroundController:
    serviceMonitor:
      enabled: true
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 512Mi
    rbac:
      clusterRole:
        extraResources:
         - apiGroups:
             - ''
           resources:
             - pods
           verbs:
             - create
             - update
             - delete
             - patch

  cleanupController:
    serviceMonitor:
      enabled: true

  reportsController:
    serviceMonitor:
      enabled: true

  grafana:
    enabled: true

  crds:
    install: true

  existingImagePullSecrets: []


policy-reporter:
  install: true

  kyvernoPlugin:
    enabled: true
  ui:
    enabled: true
    plugins:
      kyverno: true

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: "routing-oidc-forward-auth@kubernetescrd, {{ .Release.Namespace }}-strip-prefix-{{ .Release.Name }}@kubernetescrd"

  # --(String) Required, set the domain you want to serve the UI from
  host:

  rules:
    - host: "{{ .Values.ingress.host }}"
      paths:
        - path: "/policies"
        - path: "/_nuxt"

