ingressRoute:
  enabled: false
  adminDomain: "admin.my-domain.com"
  pathPrefix: "/policies`,`/_nuxt"
  entryPointName: "after-proxy"

kyverno:
  installCRDs: true
  existingImagePullSecrets: []

policy-reporter:
  install: true
  kyvernoPlugin:
    enabled: true
  ui:
    enabled: true
    plugins:
      kyverno: true
