{{- with .Values.ingress }}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "oidc-forward-auth.fullname" $ }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    iits-consulting.chart-creator/version: 1.4.0
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{ if .className }}
  ingressClassName: {{ .className }}
  {{- end }}

  tls:
    - hosts:
      {{- range .hosts }}
        - {{ tpl (toYaml .host) $ }}
      {{- end }}

  rules:
      {{- range .hosts }}
    - host: {{ tpl (toYaml .host) $ }}
      http:
        paths:
            {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix"}}
            backend:
              service:
                name: {{ include "gatekeeper.fullname" $ | quote}}
                port:
                  name: "proxy"
            {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
