{{- with .Values.ingress }}
{{- if eq .enabled true}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "elasticsearch.fullname" $ }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    iits-consulting.chart-creator/version: 1.4.0
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{ if .className }}
  ingressClassName: {{ .className }}
  {{- end }}

  tls:
    - hosts:
        - {{ tpl (toYaml .host) $ }}

  rules:
    - host: {{ tpl (toYaml .host) $ }}
      http:
        paths:
          - path: {{ tpl (toYaml .paths.kibana) | quote }}
            pathType: {{ .pathType | default "Prefix"}}
            backend:
              service:
                name: "{{ $.Release.Name }}-kibana"
                port:
                  name: "http"
          - path: {{ tpl (toYaml .paths.elasticsearch) | quote }}
            pathType: {{ .pathType | default "Prefix"}}
            backend:
              service:
                name: "{{ $.Values.elasticsearch.clusterName }}-{{ $.Values.elasticsearch.nodeGroup }}"
                port:
                  number: {{ $.Values.elasticsearch.httpPort }}
{{- end }}
{{- end }}
