apiVersion: v2
description: |
  This chart is used to bootstrap a Kubernetes cluster with `argocd`.
  You can use this chart to deploy `argocd` through tools like `terraform`.

  Usage example:

  ```hcl
  resource "helm_release" "argocd" {
    name                  = "argocd"
    repository            = "https://charts.iits.tech"
    chart                 = "argocd"
    version               = "16.3.0"
    namespace             = "argocd"
    create_namespace      = true
    wait                  = true
    atomic                = true
    timeout               = 900 // 15 Minutes
    render_subchart_notes = true
    dependency_update     = true
    wait_for_jobs         = true
    values                = [
      yamlencode({
        projects = {
          infrastructure-charts = {
            projectValues = {
              # Set this to enable stage values-$STAGE.yaml
              stage        = var.stage
              # Example values which are handed down to the project. Like this you can give over informations from terraform to argocd
              rootDomain  = var.domain_name
            }

            git = {
              password = var.git_token
              repoUrl  = "https://github.com/iits-consulting/otc-infrastructure-charts-template"
            }
          }
        }
      }
      )
    ]
  }
  ```

  In the project https://github.com/iits-consulting/otc-infrastructure-charts-template it expects a helm chart
  named infrastructure-charts and will install everything from there.

name: argocd
appVersion: 2.11.7
version: 16.2.1
dependencies:
  - name: argo-cd
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 6.6.7
