argo-cd:
  fullnameOverride: "argocd"

  controller:
    kind: StatefulSet
    replicaCount: 2
    extraEnvVars:
      - name: "TZ"
        value: "Europe/Berlin"
    logFormat: "json"
    resourcesPreset: "medium"
  dex:
    enabled: false
  notifications:
    enabled: false
  repoServer:
    extraEnvVars:
      - name: "TZ"
        value: "Europe/Berlin"
    logFormat: "json"
    resourcesPreset: "small"
    containerSecurityContext:
      seccompProfile:
        type: Unconfined
  server:
    ingress:
      enabled: true
      hostname: "SET_BY_TERRAFORM"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      path: "/argocd"
    extraEnvVars:
      - name: "TZ"
        value: "Europe/Berlin"
      - name: "ARGOCD_SERVER_ROOTPATH"
        value: "{{ .Values.server.ingress.path }}"
      - name: "ARGOCD_SERVER_BASEHREF"
        value: "{{ .Values.server.ingress.path }}"
    logFormat: json
    insecure: true

    config:
      url: "https://{{ .Values.server.ingress.hostname }}{{ .Values.server.ingress.path }}"

      oidc.config: |
        name: OIDC
        issuer: $argocd-oidc:oidcURL
        clientID: $argocd-oidc:clientID
        clientSecret: $argocd-oidc:clientSecret
        requestedScopes:
          - openid
          - profile
          - email
          - groups
        requestedIDTokenClaims:
          groups:
            essential: true

      resource.customizations: |
        # Ignores .data changes of all secrets with a vaultInjectionChecksum annotation
        argoproj.io/Application:
         ignoreDifferences: |
            jqPathExpressions:
              - '. | select(.metadata.annotations.parametersChecksum) | .spec.source.helm'
              - '. | select(.metadata.annotations.valueFileChecksum) | .spec.source.helm'
        # Ignores caBundle and template changes of the following resources
        admissionregistration.k8s.io/MutatingWebhookConfiguration:
          ignoreDifferences: |
            jqPathExpressions:
              - .metadata.annotations.template
              - '.webhooks'
        apiextensions.k8s.io/CustomResourceDefinition:
          ignoreDifferences: |
            jqPathExpressions:
              - .spec.conversion.webhookClientConfig.caBundle
        admissionregistration.k8s.io/ValidatingWebhookConfiguration:
          ignoreDifferences: |
            jqPathExpressions:
              - .metadata.annotations.template
              - '.webhooks[]?.clientConfig.caBundle'
              - '.webhooks'
        cert-manager.io/Certificate:
          ignoreDifferences: |
            jqPathExpressions:
              - .spec.duration
        networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs

  config:
    rbac:
      policy.csv: |
        g, ARGOCD-ADMIN, role:admin
        g, SYSTEM-ADMINISTRATOR, role:admin

# Please use argocd-secret chart instead if you are using keycloak deployed in the same stage to avoid cyclic dependencies.
#    secret:

# -- List of projects which you want to bootstrap
projects:
## bootstraps infrastructure related charts like traefik, elastic-stack...
#  infrastructure-charts:
## values which are handed over to the infrastructure-charts project like this you can for example give over information from terraform to argocd
#    projectValues:
#      # Set this to enable stage values.yaml
#      stage:
#    # defaults to false
#    serverSideApply:
#    # information about the git repo which should be bootstrapped
#    git:
#      # defaults to ARGOCD_GIT_ACCESS_TOKEN
#      username:
#      password: "SET_BY_TERRAFORM"
#      repoUrl: "SET_BY_TERRAFORM"
#      # defaults to main
#      branch:
#      # defaults to project name
#      path:
#      repoPrivateKeyBase64Encoded:
#
#    # helm registries credentials
#    helmRegistries:
#      infraRegistry:
#        # defaults to map key
#        name: ""
#        password: "SET_BY_TERRAFORM"
#        url: "SET_BY_TERRAFORM"
#        # defaults to ARGOCD_GIT_ACCESS_TOKEN
#        username:
#
#    # defaults to *
#    allowedUrls:

# Kyverno Policy Exception
policyException:
  enabled: true
