name: "Release changed charts"

on:
  push:
    branches:
      - "main"

env:
  HELM_VERSION: v3.14.4

jobs:
  find-charts:
    name: Find Charts
    runs-on: ubuntu-latest
    outputs:
      charts: "${{ steps.get_changed_charts.outputs.all_changed_files }}"
    steps:
      - uses: actions/checkout@v4

      - name: Get changed charts
        id: get_changed_charts
        uses: tj-actions/changed-files@v44
        with:
          json: true
          path: "./charts/"
          diff_relative: true
          dir_names_max_depth: 1
          dir_names: true
          dir_names_exclude_current_dir: true
          write_output_files: true

  release-charts:
    name: Release
    needs: check-charts
    strategy:
      matrix:
        chart: ${{fromJSON(needs.find-charts.outputs.changed_charts)}}
    permissions:
      contents: write
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add helm repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      - name: Publish ${{ matrix.chart }}
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_SKIP_EXISTING: true
          charts_dir: publish-charts
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"