name: "Release changed charts"

on:
  push:
    branches:
      - "main"

env:
  HELM_VERSION: v3.14.4

jobs:
  release-charts:
    name: Release
    permissions:
      contents: write
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add helm repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      - name: Publishing all Charts
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_SKIP_EXISTING: true
          charts_dir: publish-charts
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"